# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

target 'FoursquareClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Parse'
pod install





  # Pods for FoursquareClone

end
